groq:
  api_key: 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
  model: mixtral-8x7b-32768
  system_prompt: You are a knowledgeable expert and educator. Your task is to create comprehensive, well-structured educational content in professional HTML email format.

email:
  api_key: re_Fua1VjBd_CEDoMbg8or9QT9nnov5GmNED
  from_email: onboarding@resend.dev
  recipient_email: papepapes@gmail.com
  subject_prefix: AI Course Generator

output:
  directory: generated_courses
  filename_pattern: course_{date}.html
  date_format: '%Y%m%d_%H%M%S'

content:
  master_subject_prompt: |
    Create a master prompt that will guide an AI model in generating educational content about {subject}.
    
    The master prompt should instruct the AI to:
    1. Define the scope and key areas of {subject}
    2. Randomly select a specific topic within {subject}
    3. Create detailed educational content in HTML email format
    4. Use proper HTML email styling best practices

    Remember: This is a prompt template - don't generate the actual content, just create the instructions for generating it.

  current_master_prompt: |
    You are an expert in {subject}. Your task is to:

    1. First, randomly select ONE specific topic from your expertise in {subject}. Choose a focused, well-defined topic that:
       - Is important and relevant to {subject}
       - Can be covered comprehensively in one lesson
       - Provides practical value to learners

    2. Then, create a comprehensive educational email about your chosen topic. Output your response as a complete HTML email that follows these requirements:

    a) Use this exact HTML email template structure:
    ```html
    <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
    <html xmlns="http://www.w3.org/1999/xhtml">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
      </head>
      <body style="margin:0;padding:0;box-sizing:border-box;font-family:Arial,Helvetica,sans-serif;">
        <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="min-width:100%;background-color:#f8f9fa">
          <tr>
            <td align="center" style="padding:20px 0">
              <table role="presentation" cellpadding="0" cellspacing="0" style="width:100%;max-width:600px;margin:0 auto;background-color:white;border-radius:8px;box-shadow:0 2px 4px rgba(0,0,0,0.1)">
                <!-- Header -->
                <tr>
                  <td style="padding:24px;background-color:#2c3e50;border-radius:8px 8px 0 0;text-align:center">
                    <h1 style="margin:0;color:white;font-size:28px;line-height:1.3">[Your Topic Name]</h1>
                  </td>
                </tr>
                <!-- Content -->
                <tr>
                  <td style="padding:24px">
                    [Your Content Here: Introduction, Core Concepts, Implementation, etc.]
                  </td>
                </tr>
                <!-- Footer -->
                <tr>
                  <td style="padding:24px;background-color:#f8f9fa;border-radius:0 0 8px 8px;text-align:center">
                    <p style="margin:0;color:#666;font-size:14px">Generated by AI Course Generator</p>
                  </td>
                </tr>
              </table>
            </td>
          </tr>
        </table>
      </body>
    </html>
    ```

    b) Structure your content with these styled sections:
       - Introduction (What is this topic and why is it important?)
         Use: <div style="margin-bottom:24px">
                <h2 style="color:#2c3e50;font-size:24px;margin:0 0 16px">Introduction</h2>
                <p style="color:#2c3e50;font-size:16px;line-height:1.6;margin:0">
              </div>

       - Core Concepts
         Use: <div style="margin-bottom:24px">
                <h2 style="color:#2c3e50;font-size:24px;margin:0 0 16px">Core Concepts</h2>
                <ul style="margin:0;padding-left:24px">
                  <li style="color:#2c3e50;font-size:16px;line-height:1.6;margin-bottom:8px">
              </div>

       - Implementation Steps
         Use: <div style="margin-bottom:24px">
                <h2 style="color:#2c3e50;font-size:24px;margin:0 0 16px">Implementation Guide</h2>
                <ol style="margin:0;padding-left:24px">
                  <li style="color:#2c3e50;font-size:16px;line-height:1.6;margin-bottom:8px">
              </div>

       - Best Practices & Common Pitfalls
         Use: <div style="margin-bottom:24px;background-color:#f8f9fa;padding:16px;border-radius:4px">
                <h2 style="color:#2c3e50;font-size:24px;margin:0 0 16px">Best Practices & Common Pitfalls</h2>
              </div>

       - Practice Questions
         Use: <div style="margin-bottom:24px;background-color:#f8f9fa;padding:16px;border-radius:4px">
                <h2 style="color:#2c3e50;font-size:24px;margin:0 0 16px">Practice Questions</h2>
                <p style="color:#2c3e50;font-size:16px;line-height:1.6;margin:0 0 16px;font-weight:bold">
              </div>

    Remember:
    1. Choose only ONE specific topic from {subject}
    2. Use the exact HTML template structure provided
    3. Include all inline styles as shown
    4. Ensure all content is properly formatted with the provided section styles
    5. Make the content comprehensive but email-friendly (not too long)
